version: "3.9"
services:
  wg-crawler:
    build:
      context: .
    image: wg-crawler
    container_name: wg-crawler-container
    restart: always
    ports:
      - 4000:4000
    depends_on:
      - mongo-db
    environment:
      - MONGO_CONNECTION_STRING=${MONGO_CONNECTION_STRING}
      - SEARCH_QUERY=${SEARCH_QUERY}
      - GMAPS_KEY=${GMAPS_KEY}
      - GMAPS_DEPARTURE_WEEKDAY=${GMAPS_DEPARTURE_WEEKDAY}
      - GMAPS_DEPARTURE_TIME=${GMAPS_DEPARTURE_TIME}
  mongo-db:
    image: mongo
    container_name: mongo-db-container
    restart: always
    ports:
      - 27017:27017
